/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guilanjutan;

import javax.swing.JOptionPane;

/**
 *
 * @author santuy
 */
public class latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form latihan3
     */
    public latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        VolumeK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jariB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        VolumeB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Lebar      : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 120, 30);

        Lebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarActionPerformed(evt);
            }
        });
        jPanel1.add(Lebar);
        Lebar.setBounds(140, 70, 130, 30);

        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 70, 30, 30);

        jLabel4.setText("Masukkan Tinggi      : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 120, 30);

        jLabel5.setText("Masukkan Panjang  : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 30, 120, 30);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(140, 110, 130, 30);
        jPanel1.add(Panjang);
        Panjang.setBounds(140, 30, 130, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 110, 30, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 30, 30, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(140, 160, 100, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 30, 170, 30);
        jPanel2.add(sisiKubus);
        sisiKubus.setBounds(20, 60, 120, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 60, 50, 30);

        VolumeK.setText("Volume");
        VolumeK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeKActionPerformed(evt);
            }
        });
        jPanel2.add(VolumeK);
        VolumeK.setBounds(20, 100, 90, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 30, 200, 30);
        jPanel3.add(jariB);
        jariB.setBounds(10, 60, 130, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(150, 60, 40, 30);

        VolumeB.setText("Volume");
        VolumeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBActionPerformed(evt);
            }
        });
        jPanel3.add(VolumeB);
        VolumeB.setBounds(10, 100, 90, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        int hasil = panjang * lebar * tinggi;
        try {
            JOptionPane.showMessageDialog(null, "Volume balok adalahh : " + hasil,
                    "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Gagal", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void VolumeKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeKActionPerformed
        int sisi;
        sisi = Integer.parseInt(sisiKubus.getText());
        int hasil = sisi * sisi * sisi;

        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan kubus adalah : "
                    + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Gagal", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_VolumeKActionPerformed

    private void VolumeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBActionPerformed
        float jari;
        jari = Integer.parseInt(jariB.getText());
        float hasil1 = (float) (4 / 3 * 3.14 * jari * jari * jari);
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan bola adalah : "
                    + hasil1, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Gagal", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_VolumeBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton VolumeB;
    private javax.swing.JButton VolumeK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jariB;
    private javax.swing.JTextField sisiKubus;
    // End of variables declaration//GEN-END:variables
}
